---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-hujer.info-selfsigned
  namespace: default
spec:
  isCA: true
  commonName: selfsigned-ca-hujer.info
  secretName: selfsigned-ca-hujer.info-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
