apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: digitalocean-cloud-controller-manager
  name: digitalocean-cloud-controller-manager
  namespace: kube-system
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: digitalocean-cloud-controller-manager
