---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: security-profiles-operator
  labels:
    name: spod
spec:
  ports:
    - name: https
      port: 443
      targetPort: 9443
  selector:
    name: spod
