---

hubble:
  enabled: true
  relay:
    image:
      pullPolicy: IfNotPresent
    enabled: true
  ui:
    frontend:
      image:
        pullPolicy: IfNotPresent
    backend:
      image:
        pullPolicy: IfNotPresent
    proxy:
      image:
        pullPolicy: IfNotPresent
    # enable Hubble UI
    enabled: true
    standalone:
      # enable Hubble UI standalone deployment
      enabled: true
    ingress:
      enabled: true
      hosts:
        - hubble.127.0.0.1.nip.io
