---
global:
  image:
    tag: "v2.3.3"
    imagePullPolicy: Never
dex:
  enabled: false
controller:
  metrics:
    enabled: true
repoServer:
  image:
    imagePullPolicy: Never
  metrics:
    enabled: true
server:
  config:
    url: http://argocd.127.0.0.1.nip.io
  metrics:
    enabled: true
  extraArgs:
    - --insecure
    - --disable-auth
  ingress:
    enabled: true
    hosts:
      - argocd.127.0.0.1.nip.io
redis:
  metrics:
    enabled: true
    image:
      imagePullPolicy: Never
  image:
    imagePullPolicy: Never
