apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system-logging
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.12.0
    helm:
      values: |
        persistence:
          enabled: true
          size: 10Gi
        ingress:
          enabled: false
          # hosts:
          #  - host: loki.68.183.240.164.nip.io
          #    paths: 
          #    - /
        serviceMonitor:
          enabled: true
          prometheusRule:
            enabled: false
