apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system-logging
  source:
    chart: loki-simple-scalable
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.7.1
    helm:
      values: |
        loki:
          auth_enabled: false
        rbac:
          pspEnabled: false
        monitoring:
          serviceMonitor:
            enabled: true
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
        gateway:
          ingress:
            enabled: false
