apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system-logging
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.2.0
    helm:
      values: |
        serviceMonitor:
          enabled: true
        config:
          lokiAddress: http://loki:3100/loki/api/v1/push
          snippets:
            extraScrapeConfigs: |
              # https://github.com/WoodProgrammer/kubernetes-audit-dashboards/blob/master/promtail/promtail.yaml
              - job_name: system
                static_configs:
                  - targets:
                      - localhost
                    labels:
                      job: k8s-audit-logs
                      agent: promtail
                      __path__: /var/log/kubernetes/k8s-audit.log
