apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system-monitoring
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 31.0.0
    helm:
      skipCrds: true
      values: |
        grafana:
          enabled: true
          serviceMonitor:
            enable: true
          adminPassword: admin
          ingress:
            enabled: true
            hosts:
              - grafana.127.0.0.1.nip.io
          sidecar:
            dashboards:
              searchNamespace: ALL
            enableUniqueFilenames: true
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://loki.logging.svc:3100
                jsonData:
                  maxLines: 1000
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'system'
                orgId: 1
                folder: 'System'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/system
          dashboards:
            system:
              ingress:
                gnetId: 9614
                revision: 1
                datasource: Prometheus
              prometheus-stats:
                gnetId: 2
                revision: 2
                datasource: Prometheus
        prometheus:
          enabled: true
          ingress:
            enabled: yes
            hosts:
              - prometheus.127.0.0.1.nip.io
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
        #    scrapeInterval: 5s
        #    scrapeTimeout: 5s
        #
        kubeStateMetrics:
          enabled: true
        nodeExporter:
          enabled: true
        alertmanager:
          enabled: false
        kubeApiServer:
          enabled: false
        kubelet:
          enabled: true
        kubeProxy:
          enabled: false
        kubeControllerManager:
          enabled: false
        coreDns:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeEtcd:
          enabled: false
