apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starboard
  namespace: argocd
spec:
  project: security-starboard
  source:
    chart: starboard-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.10.4
    helm:
      values: |
#        trivy:
#          ignoreUnfixed: true
  destination:
    server: https://kubernetes.default.svc
    namespace: starboard-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clustercompliancereports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clustercompliancedetailreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: ciskubebenchreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterconfigauditreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clustervulnerabilityreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: kubehunterreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
