apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: security-falco
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 1.18.2
    helm:
      values: |
#        trivy:
#          ignoreUnfixed: true
  destination:
    server: https://kubernetes.default.svc
    namespace: falco-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
