name: dry-run in kind

on: pull_request

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          name: trivy-image-results
          node_image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
          cluster_name: security-playground
          version: 0.14.0

      - name: Show kubectl version
        run: kubectl version
