name: dry-run in kind

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows:
      - "trivy check"
      - "sh-checker"
      - "terrascan"
      - "tflint"
      - "tfsec"
    branches: [main]
    types:
      - completed

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo apt update
          sudo apt install make -y

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@main
        with:
          cluster_name: security-playground
          node_image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
          version: "v0.14.0"
          kubectl_version: "v1.24.1"
          config: "kind/kind-config.yaml"
          wait: 30s

      - name: Show kubectl version
        run: kubectl version

      - name: Show all pods
        run: sleep 10 && kubectl get pods -A

      - name: fix prometheus-operator's CRDs
        run: make kind-install-crds

      - name: install cilium
        run: make cilium-install

      - name: Show all pods
        run: sleep 10 && kubectl get pods -A

