name: dry-run in kind

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows:
      - "trivy check"
      - "sh-checker"
      - "terrascan"
      - "tflint"
      - "tfsec"
    branches: [main]
    types:
      - completed

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e
          cluster_name: security-playground
          version: 0.13.0

      - name: Show kubectl version
        run: kubectl version

      - name: Show all pods
        run: kubectl get pods -A

      #