name: helm-trivy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
#     paths:
#       - argocd/**
  push:
    branches-ignore:
      - main
#     paths:
#       - argocd/**

jobs:
  helm-trivy:
    name: Run helm-trivy
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
#       security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install pkgs
        run: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
            sudo add-apt-repository ppa:rmescandon/yq
            sudo apt update
            sudo apt install yq -y

      - name: Show yq version
        run: yq --version

      - name: show helm version
        run: helm version

      - name: run script
        run: scripts/argocd_helm_check.sh

