name: tfsec

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - main
    paths:
      - k8s-the-easy-way/**
  push:
    branches-ignore:
      - main
    paths:
      - k8s-the-easy-way/**

jobs:
  tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --exclude-downloaded-modules
          github_token: ${{ github.token }}

      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@v0.1.0
        with:
          tfsec_args: --exclude-downloaded-modules
#          sarif_file: tfsec.sarif

#      - name: Upload SARIF file
#        if: ${{ github.actor!= 'dependabot[bot]' }}
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: tfsec.sarif
